Add heroinfo command for infos about hero
Xemorr/superheroes pull request #19
Opened 2021-03-26 20:07 UTC by Repulzer

Adds the "heroinfo" command. This command got the syntax "/heroinfo <hero>"
When a "heroinfo" is set in the yml, the description will be outputted. If empty it returns a no info message

Currently I added only a Info for "Airwalker" but others will be added soon after testing/thinking about infos :)

2021-03-26 20:07 UTC, Repulzer commented
fyi: I'm **Saltyy** on discord 🍪

2021-04-21 23:55 UTC, orang3-juic3 requested changes
Review small spelling mistakes in the built in hero yml files. Eg. line 9, line 10 and line 11 of dolphin.yml contain spelling mistakes.

2021-06-05 12:01 UTC, Xemorr approved these changes

2021-06-21 23:46 UTC, Xemorr commented
I've left it too long before merging this into the project so it's no longer feasible, I have moved to HeroHandler instead of PowerHandler and many other changes. I'll consider implementing the idea into the project, just in a different form, if you want to fix the PR then feel free and I'll merge it then!

2021-06-21 23:46 UTC, closed without merging